/* This file is part of jmltoolkit project - https://github.com/jmltoolkit
 * jmltk is licensed under the Lesser GNU General Public License Version 2 and Apache License
 * SPDX-License-Identifier: LGPL-3.0-or-later Apache-2.0
 */
package io.github.jmltoolkit.lsp.highlighting

import de.uka.ilkd.key.nparser.JavaKeYLexer.*
import de.uka.ilkd.key.nparser.ParsingFacade
import org.antlr.v4.runtime.CharStreams
import org.antlr.v4.runtime.Token
import org.eclipse.lsp4j.SemanticTokens

class KeyDocumentHighlighter : DocumentHighlighter {
    override fun analyzeToken(text: String): SemanticTokens {
        val lexer = ParsingFacade.createLexer(CharStreams.fromString(text))
        val tb = SemanticTokensBuilder()
        do {
            val token = lexer.nextToken()
            if (token.type == EOF) {
                break
            }
            tokenType(token)?.let { tt ->
                tb.add(token.line - 1, token.charPositionInLine, token.text.length, tt, tokenModifier(token))
            }
        } while (token.type != EOF)
        return SemanticTokens(tb.data)
    }

    private fun tokenType(token: Token): Int? = when (token.type) {
        SL_COMMENT,
        COMMENT_END,
        DOC_COMMENT,
        ML_COMMENT,
        MODALITYD_LINE_COMMENT,
        COMMENT -> SupportedTokenTypes.COMMENT.ordinal

        MATCH_IDENT,
        IDENT
            -> SupportedTokenTypes.VARIABLE.ordinal

        ERROR_UKNOWN_ESCAPE,
        ERROR_CHAR,
            -> null

        TRUE,
        FALSE,
        BIN_LITERAL,
        HEX_LITERAL,
        INT_LITERAL,
        CHAR_LITERAL,
        REAL_LITERAL,
        DOUBLE_LITERAL,
        FLOAT_LITERAL,
            -> SupportedTokenTypes.NUMBER.ordinal

        MODALITYD_STRING,
        MODALITYD_CHAR,
        STRING_LITERAL,
        QUOTED_STRING_LITERAL,
            -> SupportedTokenTypes.STRING.ordinal

        TERMLABEL,
        MODIFIABLE,
        PROGRAMVARIABLES,
        STORE_TERM_IN,
        STORE_STMT_IN,
        HAS_INVARIANT,
        GET_INVARIANT,
        GET_VARIANT,
        IS_LABELED,
        SAME_OBSERVER,
        DEPENDINGON,
        DISJOINTMODULONULL,
        DROP_EFFECTLESS_STORES,
        ENUM_CONST,
        FREELABELIN,
        FIELDTYPE,
        FINAL,
        ELEMSORT,
        HASLABEL,
        HASSUBFORMULAS,
        ISARRAY,
        ISARRAYLENGTH,
        ISCONSTANT,
        ISENUMTYPE,
        ISINDUCTVAR,
        ISLOCALVARIABLE,
        ISOBSERVER,
        METADISJOINT,
        ISTHISREFERENCE,
        DIFFERENTFIELDS,
        ISREFERENCE,
        ISREFERENCEARRAY,
        ISSTATICFIELD,
        ISMODELFIELD,
        ISINSTRICTFP,
        NEW_DEPENDING_ON,
        NEW_LOCAL_VARS,
        NEWLABEL,
        CONTAINS_ASSIGNMENT,
        NOTFREEIN,
        STATIC,
        STATICMETHODREFERENCE,
        MAXEXPANDMETHOD,
        CLASSPATH,
        BOOTCLASSPATH,
        NODEFAULTCLASSES,
        JAVASOURCE,
        CHOOSECONTRACT,
        CONTRACTS,
        INVARIANTS,
        IN_TYPE,
        IS_ABSTRACT_OR_INTERFACE,
        IS_FINAL,
        CONTAINERTYPE,
        SORTS,
        GENERIC,
        PROXY,
        EXTENDS,
        ONEOF,
        ABSTRACT,
        ALIAS,
        SCHEMAVARIABLES,
        SCHEMAVAR,
        MODALOPERATOR,
        PROGRAM,
        FORMULA,
        TERM,
        UPDATE,
        VARIABLES,
        SKOLEMTERM,
        SKOLEMFORMULA,
        VARCOND,
        APPLY_UPDATE_ON_RIGID,
        DROP_EFFECTLESS_ELEMENTARIES,
        SIMPLIFY_IF_THEN_ELSE_UPDATE,
        HASSORT,
        DIFFERENT,
        ISSUBTYPE,
        EQUAL_UNIQUE,
        NEW,
        NEW_TYPE_OF,
        HAS_ELEMENTARY_SORT,
        NOT_,
        SAME,
        STRICT,
        TYPEOF,
        INSTANTIATE_GENERIC,
        FORALL,
        EXISTS,
        SUBST,
        IF,
        IFEX,
        THEN,
        ELSE,
        INCLUDE,
        INCLUDELDTS,
        PROGRAMSOURCE,
        WITHOPTIONS,
        OPTIONSDECL,
        KEYSETTINGS,
        PROFILE,
        SAMEUPDATELEVEL,
        IGNOREUPDATELEVEL,
        INSEQUENTSTATE,
        ANTECEDENTPOLARITY,
        SUCCEDENTPOLARITY,
        CLOSEGOAL,
        HEURISTICSDECL,
        NONINTERACTIVE,
        DISPLAYNAME,
        HELPTEXT,
        REPLACEWITH,
        ADDRULES,
        ADDPROGVARS,
        HEURISTICS,
        FIND,

        ADD,
        ASSUMES,
        TRIGGER,
        AVOID,
        PREDICATES,
        FUNCTIONS,
        DATATYPES,
        TRANSFORMERS,
        UNIQUE,
        FREE,
        RULES,
        AXIOMS,
        PROBLEM,
        PROOFOBLIGATION,
        PROOF,
        PROOFSCRIPT,
        LEMMA,
        VARIABLE,
            -> SupportedTokenTypes.KEYWORD.ordinal

        MODALITYBB,
        MODAILITYGENERIC3,
        MODAILITYGENERIC5,
        MODAILITYGENERIC6,
        MODAILITYGENERIC7,
        MODALITYD,
        MODALITYB,
        MODAILITYGENERIC1,
        MODAILITYGENERIC2,
        MODAILITYGENERIC4,
        MODALITYD_END,
        MODALITYG_END,
        MODALITYB_END,
        MODALITYBB_END,
        UTF_PRECEDES,
        UTF_IN,
        UTF_EMPTY,
        UTF_UNION,
        UTF_INTERSECT,
        UTF_SUBSET_EQ,
        UTF_SUBSEQ,
        UTF_SETMINUS,
        SEMI,
        SLASH,
        COLON,
        DOUBLECOLON,
        ASSIGN,
        DOT,
        DOTRANGE,
        COMMA,
        LPAREN,
        RPAREN,
        LBRACE,
        RBRACE,
        LBRACKET,
        RBRACKET,
        EMPTYBRACKETS,
        AT,
        PARALLEL,
        OR,
        AND,
        NOT,
        IMP,
        EQUALS,
        NOT_EQUALS,
        SEQARROW,
        EXP,
        TILDE,
        PERCENT,
        STAR,
        MINUS,
        PLUS,
        GREATER,
        GREATEREQUAL,
        OPENTYPEPARAMS,
        CLOSETYPEPARAMS,
        LESS,
        LESSEQUAL,
        LGUILLEMETS,
        RGUILLEMETS,
        EQV,
        PRIMES,
        MODALITY,
            -> SupportedTokenTypes.OPERATOR.ordinal

        else -> null
    }

    private fun tokenModifier(token: Token): Int = when (token.type) {
        else -> 0
    }
}
